global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'project-service'
    static_configs:
      - targets: ['project-service:5000']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'bom-service'
    static_configs:
      - targets: ['bom-service:5001']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'component-service'
    static_configs:
      - targets: ['component-service:5002']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
