filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/project-service/*.log
      - /var/log/bom-service/*.log
      - /var/log/component-service/*.log
    fields:
      service_type: "backend"
    fields_under_root: true
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after
    json.keys_under_root: true
    json.add_error_key: true

  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log
    fields:
      service_type: "nginx"
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
